# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Socket' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Socket
pod 'Masonry'
pod 'SocketRocket'
pod 'Charts'

end
